### ISSUE TITLE
Version numbers in the request/response and in the URL

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#10]
We have version numbers on the request/response and in the URL. The latter no longer makes sense, it should be removed.

**Comment by Relequestual** [comment]
The version numbers in the request and response only corrospond to components.
The structure of the JSON that contains those could in theory change, and that would be the version found in the URL at current.

However, if we can get the basic structure to contain the components correct, I can't see this overall structure changing in a non backwards compatible way.

Still, it will need to be versioned. HTTP content negotiation should be able to cater for our needs, aka specifying the version in the headers.

**Comment by fschiettecatte** [comment]
So we handle top level versions in the url or in the HTTP header?

**Comment by harindra-a** [comment]
I like top level version of API as a whole in URL here is possible as well, but can be convinced otherwise

**Comment by Relequestual** [comment]
There are a lot of arguments against using versioning of an API overall, but I'm not sure I generally agree with them.

Given this API is designed to be flexible, I see a move of version 1.* to version 2.* would have to be HUGE, and so putting that version number in the URL would be valid.

We do need to decide however, do we only include the Semantic Versioning "Marjor" number in the URL, as it's expected "Minor" changes are backwards compatible? (I say yes).

If so, where would we specify the complete Major.Minor.Patch version number for the API format? Header or payload?

If it's in the payload, it would increase the payload, but would probably make debugging easier.
If it's in the header, it would reduce the size of payload slightly, but could be more annoying to work with.

Any further thouhts?

**Comment by harindra-a** [comment]
All that sounds good. Regarding where to put it: I would vote we keep it in the payload as a JSON field of sorts (metadata?). I would vote we stay clear of the header, and ideally leave it only for the authentication piece..

**Comment by fschiettecatte** [comment]
Thinking about this we should put the version number of the payload in the payload itself for the reasons @Relequestual lays out above.

And we should remain silent on the format of the url except for the leaf (as is the case in MME v1). This would allow sites to define their url, and they would be free to include the Major number in there or not. 

Feel free to shoot this down :)

**Comment by Relequestual** [comment]
The argument for puttint it in a header as opposed to the payload is the payload structure might be forced to changed, while a header can be independent of the payload.

Looks like for now, general consensus is:
- major version MAY be in the URL, but this is not required
- full version number MUST be in the JSON payload. Specifically where yet to be defined, but should be reasonably obvious, like sitting within the metadata object.

I'll assign myself to this issue.

**Comment by Relequestual** [comment]
Proposed solution: https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/39

Change from spec in previous comment:
- MAJOR version must be in URL

Still need to add version number to JSON payload (Specifiying using JSON Schema).

**Comment by Relequestual** [comment]
API version included in JSON payload: https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/30/commits/ac62eeed9c5a358c2951a3300dc13db107afa7ef

**Comment by Relequestual** [comment]
#39 has been merged
