### ISSUE TITLE
Should we require default a required set of supported components?

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#15]
Do we want to require support for a minimal set of components?

**Comment by Relequestual** [comment]
I think let's table this discussion till we have a few components nailed down.

---
@harindra-a 

> I would think so. Like MME? at least gene level? Let's discuss.

[Relocated](https://github.com/ga4gh-discovery/ga4gh-discovery-search-api/issues/23#issuecomment-401909360)

**Comment by harindra-a** [comment]
agreed

**Comment by Relequestual** [comment]
I have added this to the initial release milestone as I feel we should decide on this one way or the other.

**Comment by Relequestual** [comment]
Consensus on call today:
No.
