### ISSUE TITLE
Should we allow for private / custom components?

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#17]
* Do we allow _private_ components?

---
  * ~~Do we want to support defined sets of components/records for certain communities (MME)?~~ #28 
  * ~~Why is `components` an array of objects if there is only one object?~~ #27 
  * ~~What is the process for defining new component/record types?~~ #26

**Comment by fschiettecatte** [comment]
By _private_ I mean for internal use within organizations. For example organization X has a number of internal databases and wants to use this protocol but wants to use their own `record` type. The protocol as currently defined supports this but this is not _official_.

**Comment by Relequestual** [comment]
Private components?

> My vote would be no, since it would add complexity?
@harindra-a - [Migrated](https://github.com/ga4gh-discovery/ga4gh-discovery-search-api/issues/23#issuecomment-401909360)

**Comment by Relequestual** [comment]
I think we can allow for groups to define their own components.
In the MME API, we specify that anything prefixed with an underscore is non standard. Allowing the same thing for component types should be fine I feel, and would allow for groups to define their own components. I don't think we need to call them "private" though, but that's more semantics.

**Comment by Relequestual** [comment]
Reviewing this again, I think there's no problem, with like MME, specifying that components prefixes with an underscore `_` are propritary and not defined.

~~This can be specified in the JSON Schema.~~
I don't think there is any way to specify this using JSON Schema other than for annotations.

Unless there are any objections, I'll schedule this for 0.1.0, but it can be moved to post 0.1.0 if time becomes pressing.

**Comment by Relequestual** [comment]
It turns out this is pretty tricky to specify using JSON Schema, especially if I want to maintain draft-5 backwards compatibility to eventually auto convert to OpenAPI.
Given it's part of the written spec, we don't NEED to enforce this using JSON Schema.
