### ISSUE TITLE
Define that for a search request, `components` are the search components

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#25]
#11 asks if we need to specify the versions of components in the search component.
My intention was to never have a "search component", and in stead allow `components` at the root level of a search request to represent the components to be used by a search, and then to have metadata components in the metadata object (`meta.components`).

If I can get a few nods that this makes sense, I'll make a PR.
Otherwise, we need further discussion.

(Blocks #11 )

**Comment by fschiettecatte** [comment]
This is fine with me.

**Comment by Relequestual** [comment]
It looks like after this discussion, I've defined that search components be nested under `query.components`. I think this was to align better with other proposals. (see model 2 in https://github.com/ga4gh-discovery/ga4gh-discovery-search/issues/32#issuecomment-409979513)
As such I'll close this, and #11.

@fschiettecatte Please re-open if you fee this is not OK.
