### ISSUE TITLE
Why is `components` an array of objects if there is only one object?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#27]
(Asked by @fschiettecatte)

**Comment by Relequestual** [comment]
@fschiettecatte Which `components` object are you refurring to? Is it in the request / response in this repo and / or my [proposal](https://gist.github.com/Relequestual/65c0446944519a66f8562d02b3cb4c86#response-detail)?

**Comment by fschiettecatte** [comment]
This is in the search request, in `requires => response => components`, I am not sure why the components is an array here, it feels like there will only ever be one array member that is a dictionary.

**Comment by Relequestual** [comment]
You're right. This was an error in my copy pasting in my proposal.
I've fixed it in my proposal.
I'll make a PR to fix this.

**Comment by harindra-a** [comment]
@Relequestual,  I would say just fix it in master (or do a PR and merge it yourself or François) since it looks like an error there anyway

**Comment by Relequestual** [comment]
I think that's justified in this case. I'll get on it shortly.
