### ISSUE TITLE
Should we use CURIE's or some way to identify the resource type when using IDs?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#29]
> One of the things we discussed at length in MME 1.0 was to use CURIEs for identifiers (See issue 113 in MME 1.0).
> 
> But we have a source included in the examples. It is not clear what should go there and how this is different from a CURIE. Just want to make sure we think this though.
@fschiettecatte - [Migrated](https://github.com/ga4gh-discovery/ga4gh-discovery-search-api/issues/20#issuecomment-403119721)

**Comment by Relequestual** [comment]
The [previously mentioned MME issue](https://github.com/ga4gh/mme-apis/issues/113) linked to a JSON containing a list of prefixes, which seem to have been derrived from https://prefixcommons.org.

While PrefixCommons is a collaboration between the Monarch Initiative and the Institute of Data Science @ Maastricht University, after some investigation, I also found https://identifiers.org, a service run and maintained by the EBI.

I feel that the Identifiers.org service is likely to be better maintained, and is clearer and easier to use. It's a lot clearer how new prefixes are added, and there are public APIs for accessing specific data programatically. You can do things like construct a link to the source information.

There are a number of other aspects that make Identifiers.org preferable in my opinion, which I'm happy to share should it be up for debate.

---
Should we use CURIEs? I think yes.
Where should we use CURIEs? Different question, but probably in most places where we CAN use them. I think we would have to address the issue on a case by case basis.

There are advantages to using CURIEs for genes, even if we define that currently the API only expects support for Ensembl genes (which i guess is up for debate).

---
@harindra-a this is pretty essential. I don't see any reason to NOT do this, and I think unless anyone can recomend something better than identifiers.org, or a solid reason to not use prefixes, then we should.

Adding this later would be a non backwards compatible breaking change.

**Comment by harindra-a** [comment]
let's chat about this at next meeting and iron it out, probably easier in person. I absolutely see its need, but I also see some complexity, and the fact that it was heavily debated in MME in the past. I found this thread here,
https://github.com/ga4gh/mme-apis/issues/113

**Comment by Relequestual** [comment]
Indeed, that's the linked issue above. it would be interesting to see how for example the Phenopackets specification handles gene identifiers. Edit: I'm not sure it does, oops.

**Comment by fschiettecatte** [comment]
With reference to @harindra-a's comment about the debate we had in V1, the issue was that we did not provide any context for the identifiers whereas in V2 we do in the "type" / "source" fields in the components, so the CURIE would be redundant unless we wanted it for additional checks. Perhaps it would be enough to say that the identifier be used as specified by the owner of identifier (i.e. a MIM number would be specified as 'MIM:100820' because that is what MIM specifies, HPO numbers have a similar specification, etc...)

**Comment by Relequestual** [comment]
We can specify a component must be of a perticular type, like a gene must be an ensembl gene identifier, however I expect there will be groups that want to use HGNC name or something else.

If we specify it must be an ensembl gene ID, do we specify it must include the ID prefix ENSG? I think we do.

Maybe, as you say, we need to look at this on a case by cases bases, because at some point we need to know if the field is a number or a string, and be consistent.

**Comment by harindra-a** [comment]
Why don't we keep CURIE out for the first release then? We can chat post Oct on it deeper and add it in a later release?

**Comment by fschiettecatte** [comment]
You don't need CURIEs if you specify the identifier precisely such as Ensembl, Entrez, though HGNC could be the ID or the name (symbol?). You will need a CURIE if you just say gene identifier. Not using CURIEs implies that we will need to specify identifiers precisely. As for HGNC name (symbol?), good luck to you if you want to use that.

**Comment by Relequestual** [comment]
HGNC names (symbols) are 100% not OK to use for this purpose, as they are not IDs, only names, which may get replaced at whim.

**Comment by Relequestual** [comment]
@harindra-a there isn't any decision on using CURIEs to keep, as we haven't defined how they should be determined, if at all.

As I said, I think we need to look at this on a case by case basis, and if we MUST use CURIEs, then https://identifiers.org looks like the most stable resource to take the definitions from.

Unless there are any objections, I feel we should close this issue, as it's not a definitivly answerable question.

**Comment by fschiettecatte** [comment]
I would be ok with closing this but I feel we should run it by the whole group tomorrow.

**Comment by harindra-a** [comment]
I agree. As @fschiettecatte said, lets run it by meeting tomorrow and if no one objects (I doubt anyone will) we close it (or push it post-Oct)

**Comment by Relequestual** [comment]
Agreed to close and evaluate on a case by case basis.

**Comment by mcourtot** [comment]
Re dereferencing CURIEs (with apologies for commenting on a closed issue, but AFAIK this tracker also serves as discussion archive): the OLS service at EMBL-EBI provides CURIE resolution based on identifiers.org. We have been using it successfully for a little while and were planning on keeping doing that for the metadata schema work.

**Comment by Relequestual** [comment]
Thanks @mcourtot, Good to hear it being used successfully. We will definitly keep that in mind should we re-open or recreate this issue!
