### ISSUE TITLE
Replace `disclaimer` with `acknowledgments`

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#31]
As discussed in #2, this is a suggestion to replace:
```
"disclaimer" : {
  	"version": "<semantic version>",
  	"text": "Disclaimer text...",
  	"terms" : "Terms text..."
  },
```
with:
```
"acknowledgments" : {
  	"version": "<semantic version>",
  	"disclaimer": "Disclaimer text...",
  	"terms" : "Terms text...",
  	"reference" : "Reference text...",
  },
```

This is a little more generic and add a reference for the data that is returned in the response.

All text should be in a form that can be displayed to a human, and the reference should be a in a format that can be included in a published text should the data be used.

**Comment by Relequestual** [comment]
Should https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/30/commits/cd2acd72b79046474a50a6cd788aeae31615409f get merged, does this look OK as a resolution to you?

**Comment by Relequestual** [comment]
Component's versions will be specified in metadata.

**Comment by Relequestual** [comment]
Do you think `acknowledgments` should be a "response meta component" or remain in `records.collectionComponents`?

I feel like the correct place for it would be as a response meta component, as it isn't actually pard of the record.

**Comment by fschiettecatte** [comment]
Agreed with making it a response meta component.

**Comment by Relequestual** [comment]
Done with https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/30/commits/ffeadb40da1e15cde5076219635c12681adf4712

**Comment by Relequestual** [comment]
Modified to allow single or array of acks: https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/30/commits/3f2c3098fe13113081fbda0110ca5639a2160ef2
