### ISSUE TITLE
Define component for Gene

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#43]
For the initial release, a "gene" component needs to be specified.
For now, I'm going to follow as defined by MME and suggested for 2.0, Ensembl Gene ID.

**Comment by Relequestual** [comment]
Proposed solution: https://github.com/ga4gh-discovery/ga4gh-discovery-search/pull/30/commits/79f42402e24fdfd60155a4fc01012544eda01a83

**Comment by harindra-a** [comment]
yeah, that's a great starting point
