### ISSUE TITLE
Compatibility issue with 'Expect' HTTP header

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#47]
The API version response can be specified in the [`'Expect'` HTTP header](https://github.com/ga4gh-discovery/ga4gh-discovery-search#expectations). Unfortunately this conflicts with the [`'Expect'` HTTP header specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect). Additionally Apache rejects a request with an `Expect` content other than `'100-continue'`.

One solution would be to use `'X-Expect'` as the  HTTP header for this.

**Comment by Relequestual** [comment]
I'm inclined to suggest `X-GA4GH-Discovery-Expect`. I think the name is probably inconsequential, but good to avoid name clashes.

**Comment by fschiettecatte** [comment]
I agree on both counts.

**Comment by Relequestual** [comment]
That would be the simplest option, however...
The "correct" way to do this is using an "Accept" header.

I've learnt more about that specification today!
Similar to MME, we would specify the Accept as...
`application/vnd.ga4gh.discovery.search+json`
but the version can be as a separate "extension paramiter". 
https://tools.ietf.org/html/rfc7231#section-5.3.2

So like the following:
`Accept: application/vnd.ga4gh.discovery.search+json;expect=1`
It's possible to also express a priority order if you wish...

```
Accept: 
application/vnd.ga4gh.discovery.search+json;expect=2;q=1,
application/vnd.ga4gh.discovery.search+json;expect=1.8;q=0.9
```

Having said all that... there's a reason that so many APIs still go for the simpler option... the requirements are not there for a more complex solution.

I'm going to go ahead and write up using a header of `X-GA4GH-Discovery-Expect`

**Comment by fschiettecatte** [comment]
I have to admit I like the `Accept`, elegant but, as you say, over-designed for our purposes. 

I guess it depends on how much you want future implementors to hate us.

**Comment by Relequestual** [comment]
Based on the fact I'll be making another PR tomorrow, there's no harm in reviewing this one if you so wish.

**Comment by Relequestual** [comment]
The "better" solution is sometimes the one that does the job.
New major versions are breaking changes anyway... If the technical people implementing this want a more robust solution for versioning, and this scales really well, then sure, the "proper" solution it is.
