### ISSUE TITLE
Allow a response to express results from multiple data sources

### ISSUE THREAD

**Issue by colinveal** [ga4gh-discovery/ga4gh-case-discovery#48]
Sorry if this is already solved or duplicate..
In Cafe Variome we often host multiple datasets from different 'sources', is there a way in collectionComponents (ie an array of results components) to keep the results separate for each of these sources with a key for a source ID.

**Comment by fschiettecatte** [comment]
Hasn't been brought up but it is a very good point. With MME the assumption is that there was only one collection/index/database/source. 

I am not a fan of adding a source ID in the results, I think it would be preferable to specify the collection in the search request. It does raise a bunch of questions though:

- Do we define this in the search request or via different endpoints?
- Would we need a way to discover which collections are on a server?
- Would we want to specify a default collection if none is defined in the search?
- Do we even want to deal with this in V1?

**Comment by colinveal** [comment]
As you note, the problem with specifying the collection (or combination of collections) is that they would need to know this information before sending the request whether this was in the api or via individual endpoints. Also I wouldn't really want to create a new endpoint for every collection (could be hundreds).
  
Having an array in the collectionComponents allows multiple results with minimal impact on sites with single databases as it would just add a [0] to current processing. A source 'label' could be optional and would only be needed for multi database sites and could always be ignored by receivers (i.e just total the  counts)

An alternative would be to keep the current output (using totalled counts across collections) and have a separate component class within collectionComponents that contained the splits by collection.

The majority of Cafe Variome installations have multiple collections, so a robust solution would be important for us moving forward, but not necessarily essential for V1

**Comment by Relequestual** [comment]
I did think about this and there are number of complex issue to consider when supporting endpoints which refederate the query across other resources.

As you say, any solution needs to be robust, and I didn't have the time to build in support for this within the time constraints imposed for v1.

I'm happy to take on this work adding support for this.

For v1, I think the way you can differenciate individual records as coming from different sets are to specify a link to information about the set using the Record Meta [`links` component](https://github.com/ga4gh-discovery/ga4gh-discovery-search/blob/master/json_schema/schemas_source/components/record_meta/links.yaml).

This component places no constraint on the name of a URL.

---

As I said, I've been thinking about the implications of supporting this, however it would be useful if you could provide all the metadata about each collection that you capture. This could be used to better inform any new components as required.

**Comment by Relequestual** [comment]
This is now re-scoped to be included in v1 as a result of reviewing feedback from RC5 as per https://github.com/ga4gh-discovery/ga4gh-case-discovery/issues/78

**Comment by mcupak** [comment]
LGTM! I made a minor change to the example so that it renders correctly on SwaggerHub and in Swagger Editor.
