### ISSUE TITLE
Create JSON Schema for basis of request and repsonse

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#6]
Given my [proposal](https://gist.github.com/Relequestual/65c0446944519a66f8562d02b3cb4c86) seems to have been boradly accepted, and work to merge it in has already begun, it clear (to me) that JSON Schema documents are required to formally define some aspects of the JSON structure.

My intension is for these to be mainly informative, and not assume that all implementers will use the schemas, but they SHOULD use the schemas where possible.

This issue sets out to achive the following:

- [x] Create a base request and response JSON Schema
- [x] Use references to modularise parts of the schema
- [x] Separate components into individual files

**My expectations are to have a PR ready by 2018/08/16** at the latest, which is roughly two and a half working weeks.

**Comment by Relequestual** [comment]
I have created the base schema files and a few example components.
https://github.com/Relequestual/ga4gh-discovery-search-api/tree/json-schema
I'll make a PR shortly. I'll later add a readme.md.

The source for these are in in YAML.
Run `npm install` followed by `npm run yaml2json` to conver the YAML files to JSON, if you find JSON easier to read. YAML supports multi line content, which makes comments and descriptions easier to read.

I'll be adding some npm run commands to compile the request and response schemas to transclude any use of $ref, resulting in a single request and response JSON file, but these should not be edited. Humans should read YAML, machines should read the compiled (and possibly transcluded) JSON.

@harindra-a @fschiettecatte Hopefully this adequately demonstrates the component based JSON system. If you're not familiar or rusty with JSON Schema, let me know if you have any especific questions.

(One specific immdiate comment, the URLs used in $id fields are for identifiers only, and are not required to be network accessible.)

**Comment by Relequestual** [comment]
Further work to do on JSON Schema migrated to https://github.com/ga4gh-discovery/ga4gh-discovery-search/issues/55

**Comment by fschiettecatte** [comment]
@Relequestual What are your thoughts on the interplay between JSON Schema and OpenAPI? You have mentioned using the latter before but not the former.

**Comment by Relequestual** [comment]
Assuming you mixed "latter" and "former" here...
OpenAPI 3 uses JSON Schema draft-5 for payload definitions.
OpenAPI can be used to define the API endpoints, but if there's only one endpoint, it seems a little overkill, as we're mostly interested in the request and response payload. That being said, I'm not opposed to defining an OpenAPI document, which can reference the existing JSON Schema files.

I've used the latest (draft-7), which adds a few nice things since 5, but I believe it's backwards compatible in a way which wouldn't cause any issues when used in OpenAPI.

Open to more comments / thought.

**Comment by Relequestual** [comment]
~~Based on recent emails to the group from Tony Brookes, it looks like rather than present a proposal for the Search API format before implementing, his group and Illumina will put together and implement a solution that they feel will work for everyone.~~

~~As such, I don't know if it's condusive to continue to work on my proposed solution, with the sight to modify the spec documents to conform. (Regardless, there are a number of blocking issues that still need to be resolved, which have been included in the initial release milestone).~~

~~@harindra-a I guess this is your call, as you're looking for this first implementation to reflect the first release of the API at the GA4GH plenary start of Oct. I feel it's risky to mark something as a first version without any chance for driver projects to input or feedback on the solution. (I believe neither Tony or Illimina represent a Driver Project in this context).~~

Edit: I was under false impressions. My mistake!

**Comment by harindra-a** [comment]
Hi @Relequestual, the effort by Tony and Illumina is their own effort and between Illumina and CafeVariome as far as I know. Tony is of course welcome to present his proposal and we can take pieces/inspiration of it (as we did from yours) as needed. Nara/François/me/you/others from MME and Elixir/other drivers etc, coming to Search meetings are driver representatives, so the SearchAPI IS driver driven, and part of the GA4GH official roadmap and we have to deliver. Illumina has confirmed to me (last week again) they will be compliant and a reference of our SearchAPI as well.

**Comment by Relequestual** [comment]
Ah OK, my apologies, I missunderstood! I was under the impression that that mentioned effort was to be the reference implementation required for releasing a standard, required by GA4GH processes. =]
