### ISSUE TITLE
Remove questions from spec document in favour of issues

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#7]
For the purpose of raising the issue for not including questions in the spec document, and in stead creating new issues for each question. This allows discussion on each topic without confusion.

PR welcome. Will do it myself if time allows.

- [x] Remove any questions from the documents, creating a new issue for each.

**Comment by fschiettecatte** [comment]
Questions has been removed from the [fs-updates branch](https://github.com/ga4gh-discovery/ga4gh-discovery-search-api/tree/fs-updates), if ok feel free to close this issue.
