### ISSUE TITLE
Demonstrate what can be built

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#71]
As mentioned in the RC5 Retrospective document:

Can Beacon API functionality be replicated using the Search API? Yes.
We need to demonstrate the flexibility and power of the Search API.

**Comment by kemp-google** [comment]
I can take a look at this (eg as a simple example built on top of the existing open source beacon server we have).

**Comment by Relequestual** [comment]
I think this is now out of scope given that the Case Discovery API looks to solve a single use case, and therefore does not need to demonstrate multiple use cases.
