### ISSUE TITLE
Show how collected use cases are accommodated

### ISSUE THREAD

**Issue by mcupak** [ga4gh-discovery/ga4gh-case-discovery#74]
There are currently 2 documents containing use cases from driver projects and various groups of GA4GH (that I'm aware of): [old use case document](https://docs.google.com/document/d/1JPUQpqATUObM_mxPqMNxVtEGiIhuMK5x5zt1G6PnnFg/edit#heading=h.l702kseftu0), [new use case document](https://docs.google.com/document/d/1IseLxLSlhN2-PI0_ZFkieClSa3q70MJGZS5XxO-meCQ/edit#heading=h.xt89zansanow).

Some of them are rather complex and it's not immediately clear to me if they can be accommodated by the API. Show that this can be done, or update the API to make it possible.

**Comment by kemp-google** [comment]
This would be very helpful to me as a newcomer to the conversation.  I would greatly appreciate clarity around the use cases and how they can be translated into queries against the API.

**Comment by Relequestual** [comment]
Super. This looks like it should be a high priority!

**Comment by Relequestual** [comment]
I've done some tidying of the documents in the GA4GH Search API Google Drive folder.

I've separated the responses from Driver Projects to the use case collection document, from other non Driver Project feedback and ideas.

Currently, from what I can tell, we only have TWO official responses from the use case collection document, although one of them covers two Driver Projects.

I'd like for the validation of the specification to be based mainly on the official responses from Driver Projects.

I'm not suggesting we shouldn't cover use cases presented by individuals and non-officially contributed use cases, but we have to be stategic in terms of prioritisation, which should be Driver Project feedback.

**Comment by Relequestual** [comment]
Looking at the two linked documents from the first post, most of the use cases presented by users are to do with types of data. The components architecture means that any type of data is supported as long as someone has defined the schema.

Can either of you (or anyone else) draw out some requirements which are not related to specific data types?

For example, the ability to limit the results and support pagination is an issue not yet covered by the Search API (It was agreed it would be post v1.0.0, but I'm re-opening that as an option). https://github.com/ga4gh-discovery/ga4gh-discovery-search/issues/14

**Comment by Relequestual** [comment]
OR, if there are queries you feel are complex and you'd still like to see how it could work with the components structure, please let me know!

@mcupak @kemp-google

**Comment by mcupak** [comment]
@Relequestual Sounds good, I'll take a look in the next couple of days and document here. Thanks!

Any feedback is valuable and we don't have a lot of it from DP, so I wouldn't discard the responses just because they're not in some official format, but I agree with the DP-first approach. I also think it could be valuable to demonstrate the use cases that have to do with types of data even if it's just about showing components, as it might not be immediately obvious how to implement this to people coming from outside, and it's a good sanity check for us too. We can also further use this to guide people to adopt the API.

**Comment by mcupak** [comment]
Superseded by https://github.com/ga4gh-discovery/ga4gh-search/issues/1.
