### ISSUE TITLE
Agree on consensus based on RC5 feedback

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#79]
This comment will be updated with issues to be agreed on as in scope.

Issues arrising from RC5 feedback:
- [ ] Allow a response to express results from multiple data sources https://github.com/ga4gh-discovery/ga4gh-case-discovery/issues/48
- [ ] Update authentication protocol to use JWT https://github.com/ga4gh-discovery/ga4gh-case-discovery/issues/85

Other RC6 issues resulting from prior GA4GH SC feedback: https://github.com/ga4gh-discovery/ga4gh-case-discovery/milestone/5

**Comment by Relequestual** [comment]
@colinveal, @jhkbg, @taspapak, if you can agree with the above being the outstanding issues to resolve for RC6, then this issue can be closed and further work can continue.

**Comment by colinveal** [comment]
@Relequestual yes I agree these are the outstanding issues to resolve for RC6

**Comment by Relequestual** [comment]
No further discussion on call. OK to close.
Please re-open if required.
