### ISSUE TITLE
Single specification document rather than one for search and one for response

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-discovery/ga4gh-case-discovery#8]
Given it looks like we're planning to adopt aspects of my [proposal](https://gist.github.com/Relequestual/65c0446944519a66f8562d02b3cb4c86), it makes sense to combine the request and response documents into a single spec document.

Doing so will make it more manageable.

(It's expected that each component will be housed in it's own file/s, possible markdown as well as JSON Schema.)

**Comment by mcupak** [comment]
How about writing this in OpenAPI? It seems all the necessary information is in the .md files already, and it's a format widely used in other GA4GH groups.

**Comment by Relequestual** [comment]
@mcupak Hi Miro. Given it's expected there will only be a single endpoint, it seems rather pointless to wrap the request and response in the OpenAPI layer. The request and response part of OAPI IS JSON Schema.

Of course if you can think of any benifits, I'd be more than happy to hear them.

It may be worth doing for the Service Registry project, but I'm not sure about the Search API.

**Comment by fschiettecatte** [comment]
Would be good if GA4GH would specify whether OpenAPI, JSON Schema, or either, or any at all should be used, so that there is consistency across project.

**Comment by harindra-a** [comment]
I don't think GA4GH imposes anything here, it's really upto the WS. I think down the road some consensus might appear here though. @rishidev that sounds right?

**Comment by mcupak** [comment]
I don't think anything is imposed either, but there has been some convergence on OAS. Even with a single endpoint, there are ambiguities (parameters, request methods, headers etc.), we've seen this painfully in the early days of Beacon, so IMHO there's no disadvantage to using OAS.

It should also be noted there's a lot of nice tooling around OAS (validation, compliance testing, server/client generating etc.), which could be useful (not sure about JSON schema alone). 

I think the main benefit would be easy integration with other APIs, for example DOS, consent codes, or ADA-M, which seem like good things to integrate with, are all specified in this format.

If JSON schema gives you everything you need though, that's fine too!

**Comment by harindra-a** [comment]
cool. My feeling is we go initially with what gets us through our timeline (Aug 1st, then Oct), which is what Ben has in place, and then evaluate if any change is needed post October. Just to save cycles give our pretty tight timeline

**Comment by Relequestual** [comment]
> @mcupak : Even with a single endpoint, there are ambiguities (parameters, request methods, headers etc.), we've seen this painfully in the early days of Beacon, so IMHO there's no disadvantage to using OAS.

OK, sounds like solid reasoning.

I've defined the schemas in draft-7, but I don't see us using anything which isn't backwards compatible to draft-4 (which is currently what the OpenAPI specification defines to use). There are some nice things we might want to use from draft-7 (like conditionality), but we can get away without them.

In terms of tooling, there's ample support for validation libraries.
There are tools for model generation in many languages too, if required.
Obviously there are no tools for compliance testing or server / client generation, as JSON Schema is primerily for validation. Although I'm not totally sure what you mean by compliance testing.

**Comment by Relequestual** [comment]
> @mcupak: I think the main benefit would be easy integration with other APIs, for example DOS, consent codes, or ADA-M, which seem like good things to integrate with, are all specified in this format.

Could you expand on this please? In what way would using OpenAPI aid intergration with services which also use OpenAPI?

**Comment by Relequestual** [comment]
@harindra-a Given I've actually ended up creating two (JSON Schema) documents, one for request and one for response, I think this issue is pretty null and void.

I think the reason I raised this issue was to do with the markdown documentation in the repo.

@mcupak Maybe we should move the OpenAPI discussion to a new issue, flagged as post 0.1.0, would that be OK? I Major version 0 according to semver doesn't mean much to be honest.

**Comment by Relequestual** [comment]
I'm going to close this issue, as I now dissagree with my suggestion of having a single page rather than a separate request and response page.

@mcupak If you get round to creating a new issue for OpenAPI usage, please reference this issue. I have done a little research and a I think the benefits to using it are huge.
